services:
  franken:
    container_name: sc-franken
    build:
      context: ./docker/franken
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    volumes:
      - ./:/app
    command: ["sh", "-c", "echo \"Starting infinite wait loop...\"; while sleep 1; do :; done"]
    extra_hosts:
      - "host.docker.internal:host-gateway"